# Scikit Learn Preprocessing

In [14]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
data = np.random.randint(0,100,(10,2))

In [3]:
data

array([[68, 20],
       [68, 34],
       [99, 55],
       [ 9, 66],
       [90, 83],
       [69, 57],
       [44, 82],
       [92, 41],
       [57, 34],
       [13, 11]])

In [4]:
scaler_model = MinMaxScaler()

In [5]:
scaler_model.fit(data)

C:\Users\Jayuk\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [6]:
scaler_model.transform(data)

array([[0.65555556, 0.125     ],
       [0.65555556, 0.31944444],
       [1.        , 0.61111111],
       [0.        , 0.76388889],
       [0.9       , 1.        ],
       [0.66666667, 0.63888889],
       [0.38888889, 0.98611111],
       [0.92222222, 0.41666667],
       [0.53333333, 0.31944444],
       [0.04444444, 0.        ]])

In [7]:
result = scaler_model.fit_transform(data)

C:\Users\Jayuk\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
result

array([[0.65555556, 0.125     ],
       [0.65555556, 0.31944444],
       [1.        , 0.61111111],
       [0.        , 0.76388889],
       [0.9       , 1.        ],
       [0.66666667, 0.63888889],
       [0.38888889, 0.98611111],
       [0.92222222, 0.41666667],
       [0.53333333, 0.31944444],
       [0.04444444, 0.        ]])

In [10]:
data  = pd.DataFrame(data=np.random.randint(0,101,(50,4)), columns=['f1', 'f2', 'f3', 'label'])

In [11]:
data.head(10)

f1  f2  f3  label
0  64  92  86     47
1  99   8  11     43
2  71  79   1     88
3  51  70  67     75
4   1  92  74     48
5   2   0  27     33
6  41  82  74     71
7   1  17  48     64
8   4  46  93     52
9  19  88  71     98

In [12]:
x = data[['f1', 'f2', 'f3']]
y = data['label']

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [23]:
X_train.shape

(40, 3)

In [24]:
X_test.shape

(10, 3)

In [25]:
Y_train.shape

(40,)

In [26]:
Y_test.shape

(10,)